### PR TITLE
Psi fixes

### PR DESCRIPTION
**Pull request by dirk-zimoch**
A bunch of fixes and extensions we at PSI had added over the last years, rebased onto the current master branch.

* Support for Lexium controllers
* Fix JOGR velocity sign
* Fix deceleration velocity
* Add homing flag
* Add encoder readout
* Add stall detection
* Fix many compiler warnings (unused and uninitialized variables, type mismatches, etc)
* Fix mismatch between format string and parameters

### CODE REVIEW

**Comment by kmpeters** [comment]
The checks are failling because this URL from ci-scripts is not currently accessible:

https://github.com/epics-base/ci-scripts/blob/a8bffdcfb73e7710662185d77e7cc0662a1deede/defaults.set#L21

www-csr.bessy.de appears to be down:

https://downforeveryoneorjustme.com/www-csr.bessy.de?proto=https

**Comment by kmpeters** [comment]
I'll merge this pull req after www-csr.bessy.de is back and the checks succeed.

**Comment by kmpeters** [comment]
@dirk-zimoch, I switched the master branch to use the mirror of the sequencer repo.  If you merge this commit into the pull req branch, the ci build should succeed:

https://github.com/epics-motor/motorIms/commit/22a5f8295b582518eace8de64ceb39de70ab33b0

**Comment by kmpeters** [comment]
I tried merging the master branch into the psi-fixes branch, which appeared to succeed:

https://github.com/dirk-zimoch/motorIms/commit/cfb9eb7f1a2cebd9b94d997bde9df4a3ea735d26

But this pull req isn't updating yet.

**Comment by dirk-zimoch** [comment]
Hi Kevin,
I was on vacation. Anything left I need to do?
Dirk

**Comment by kmpeters** [comment]
@dirk-zimoch, I don't think so.  There was some weirdness in this PR branch (I merged the change from master that switched to the sequencer mirror and this PR didn't get automatically rebuit).  When I merged this PR, everything built succesfully.

**Pull request merged**
